create table if not exists public.developers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text not null,
  slug text unique not null,
  title text,
  skills text,
  experience_years int default 0,
  github_url text,
  linkedin_url text,
  portfolio_url text,
  bio text,
  profile_image text,
  open_to_work boolean default false,
  created_at timestamptz default now()
);

create index if not exists developers_slug_idx on public.developers(slug);
create index if not exists developers_open_to_work_idx on public.developers(open_to_work);

create table if not exists public.email_otps (
  id bigint generated by default as identity primary key,
  email text not null,
  otp text not null,
  used boolean default false,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

alter table public.developers enable row level security;
alter table public.email_otps enable row level security;

drop policy if exists "developers public read" on public.developers;
create policy "developers public read" on public.developers for select using (true);
drop policy if exists "developers public upsert" on public.developers;
create policy "developers public upsert" on public.developers for insert with check (true);
create policy "developers public update" on public.developers for update using (true) with check (true);

drop policy if exists "otp insert" on public.email_otps;
create policy "otp insert" on public.email_otps for insert with check (true);
drop policy if exists "otp read" on public.email_otps;
create policy "otp read" on public.email_otps for select using (true);
drop policy if exists "otp update" on public.email_otps;
create policy "otp update" on public.email_otps for update using (true) with check (true);
