-- Run this in Supabase SQL editor
create table if not exists public.developers (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  title text not null,
  skills text not null,
  experience_years integer not null default 0,
  github_url text,
  linkedin_url text,
  portfolio_url text,
  bio text,
  profile_image text,
  open_to_work boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.developers enable row level security;

create policy "Public read developers"
on public.developers
for select
using (true);

create policy "Public insert developers"
on public.developers
for insert
with check (true);

create index if not exists developers_slug_idx on public.developers (slug);
create index if not exists developers_created_at_idx on public.developers (created_at desc);
